import { deepFreeze, type CompatibilityStatus, type DocumentationEvidencePath } from './public-contract';

export interface CompatibilityEntry {
  readonly id: string;
  readonly directiveFamily: string;
  readonly category: 'flex' | 'visibility' | 'grid' | 'responsive-class-style' | 'images';
  readonly tailwind: CompatibilityStatus;
  readonly css: CompatibilityStatus;
  readonly evidence: readonly DocumentationEvidencePath[];
}

const evidence = [
  'docs/compatibility.md',
  'test/compatibility/compatibility-inventory.ts',
  'test/compatibility/compatibility-inventory.test.ts',
] as const;

export const compatibilityReference = deepFreeze([
  {
    id: 'fxLayout',
    directiveFamily: 'Flex',
    category: 'flex',
    tailwind: 'limited',
    css: 'limited',
    evidence,
  },
  {
    id: 'fxLayoutAlign',
    directiveFamily: 'Flex',
    category: 'flex',
    tailwind: 'limited',
    css: 'limited',
    evidence,
  },
  {
    id: 'fxLayoutGap',
    directiveFamily: 'Flex',
    category: 'flex',
    tailwind: 'limited',
    css: 'limited',
    evidence,
  },
  {
    id: 'fxFlex',
    directiveFamily: 'Flex',
    category: 'flex',
    tailwind: 'limited',
    css: 'limited',
    evidence,
  },
  {
    id: 'fxGrow',
    directiveFamily: 'Flex',
    category: 'flex',
    tailwind: 'limited',
    css: 'limited',
    evidence,
  },
  {
    id: 'fxShrink',
    directiveFamily: 'Flex',
    category: 'flex',
    tailwind: 'limited',
    css: 'limited',
    evidence,
  },
  {
    id: 'fxFlexAlign',
    directiveFamily: 'Flex',
    category: 'flex',
    tailwind: 'limited',
    css: 'limited',
    evidence,
  },
  {
    id: 'fxFlexFill',
    directiveFamily: 'Flex',
    category: 'flex',
    tailwind: 'limited',
    css: 'limited',
    evidence,
  },
  {
    id: 'fxFill',
    directiveFamily: 'Flex',
    category: 'flex',
    tailwind: 'limited',
    css: 'limited',
    evidence,
  },
  {
    id: 'fxFlexOffset',
    directiveFamily: 'Flex',
    category: 'flex',
    tailwind: 'limited',
    css: 'limited',
    evidence,
  },
  {
    id: 'fxFlexOrder',
    directiveFamily: 'Flex',
    category: 'flex',
    tailwind: 'limited',
    css: 'limited',
    evidence,
  },
  {
    id: 'fxShow',
    directiveFamily: 'Visibility',
    category: 'visibility',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'fxHide',
    directiveFamily: 'Visibility',
    category: 'visibility',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'gdAlignColumns',
    directiveFamily: 'Grid',
    category: 'grid',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'gdAlignRows',
    directiveFamily: 'Grid',
    category: 'grid',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'gdArea',
    directiveFamily: 'Grid',
    category: 'grid',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'gdAreas',
    directiveFamily: 'Grid',
    category: 'grid',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'gdAuto',
    directiveFamily: 'Grid',
    category: 'grid',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'gdColumn',
    directiveFamily: 'Grid',
    category: 'grid',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'gdColumns',
    directiveFamily: 'Grid',
    category: 'grid',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'gdGap',
    directiveFamily: 'Grid',
    category: 'grid',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'gdGridAlign',
    directiveFamily: 'Grid',
    category: 'grid',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'gdInline',
    directiveFamily: 'Grid',
    category: 'grid',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'gdRow',
    directiveFamily: 'Grid',
    category: 'grid',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'gdRows',
    directiveFamily: 'Grid',
    category: 'grid',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'class',
    directiveFamily: 'Class/style',
    category: 'responsive-class-style',
    tailwind: 'preserved',
    css: 'preserved',
    evidence,
  },
  {
    id: 'ngClass',
    directiveFamily: 'Class/style',
    category: 'responsive-class-style',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'style',
    directiveFamily: 'Class/style',
    category: 'responsive-class-style',
    tailwind: 'preserved',
    css: 'preserved',
    evidence,
  },
  {
    id: 'ngStyle',
    directiveFamily: 'Class/style',
    category: 'responsive-class-style',
    tailwind: 'limited',
    css: 'preserved',
    evidence,
  },
  {
    id: 'imgSrc',
    directiveFamily: 'Image',
    category: 'images',
    tailwind: 'not-applicable',
    css: 'not-applicable',
    evidence,
  },
] as const satisfies readonly CompatibilityEntry[]);
