import type { LocatedFlexLayoutInput } from '../../analyzer/flex-layout-attribute.analyzer';
import type { ConversionAdapter, ConversionContext, PlannedConversion } from '../conversion-adapter';
import { planLayoutGap } from './directives/layout-gap.strategy';
import { planFlexItem } from './directives/flex-item.strategy';
import { planFlexOffset } from './directives/flex-offset.strategy';
import type { TailwindStrategyResult } from './tailwind-semantic.model';
import { planLayoutAlign } from './directives/layout-align.strategy';
import { planIndependentDirective } from './independent-directive.registry';
import type { TemplateAttribute } from '../../template/template.model';
import { planLayout } from './directives/layout.strategy';
import { hasTailwindClassConflict } from './tailwind-class-conflict';
import { BreakpointCatalog } from '../../breakpoint/breakpoint-catalog';
import { ResponsiveVariantEmitter } from './responsive-variant.emitter';
import { planResponsiveClasses } from './responsive-plan';

const flexItemDirectives = new Set<LocatedFlexLayoutInput['directive']>(['fxFlex', 'fxGrow', 'fxShrink']);

const supportedDirectives = new Set<LocatedFlexLayoutInput['directive']>([
  'fxFlex',
  'fxFlexAlign',
  'fxFlexFill',
  'fxFill',
  'fxFlexOffset',
  'fxFlexOrder',
  'fxLayout',
  'fxLayoutAlign',
  'fxLayoutGap',
]);

function toPlannedConversion(input: LocatedFlexLayoutInput, result: TailwindStrategyResult): PlannedConversion {
  if (result.status === 'converted') return { status: 'converted', input, classNames: result.classNames };
  if (result.status === 'invalid') {
    return {
      status: 'invalid',
      input,
      code: result.code,
      reason: `${input.value} is not a supported ${input.directive} value.`,
      suggestion: 'Correct the value or migrate this directive manually.',
    };
  }
  return { ...result, input };
}

function toResponsivePlannedConversion(
  input: LocatedFlexLayoutInput,
  result: TailwindStrategyResult,
  catalog: BreakpointCatalog,
  emitter: ResponsiveVariantEmitter,
): PlannedConversion {
  return toPlannedConversion(
    input,
    result.status === 'converted' ? planResponsiveClasses(input, result.classNames, catalog, emitter) : result,
  );
}

function preserveRequiredLayoutContext(plans: readonly PlannedConversion[]): readonly PlannedConversion[] {
  const unresolvedDependent = plans.some(
    plan =>
      (plan.input.directive === 'fxLayoutGap' || plan.input.directive === 'fxLayoutAlign') &&
      plan.status !== 'converted',
  );
  if (!unresolvedDependent) return plans;
  return plans.map(plan =>
    plan.input.directive === 'fxLayout' && plan.status === 'converted'
      ? {
          status: 'review',
          input: plan.input,
          code: 'context-unverified',
          reason: 'This layout is required to preserve an unresolved context-dependent directive.',
          suggestion: 'Migrate the layout and its dependent directives together after resolving their behavior.',
        }
      : plan,
  );
}

function staticLayoutContext(attributes: readonly TemplateAttribute[]): string | undefined {
  const layouts = attributes.filter(
    attribute => attribute.name === 'fxLayout' || attribute.name.startsWith('fxLayout.'),
  );
  if (!layouts.length) return 'row';
  if (layouts.length !== 1) return undefined;
  const layout = layouts[0];
  return layout?.name === 'fxLayout' && layout.binding === 'literal' ? layout.value : undefined;
}

export class TailwindAdapter implements ConversionAdapter {
  readonly name = 'tailwind' as const;
  private readonly breakpointCatalog = new BreakpointCatalog();
  private readonly responsiveEmitter = new ResponsiveVariantEmitter();

  resolveClassConflicts(
    plans: readonly PlannedConversion[],
    existingClassNames: readonly string[],
  ): readonly PlannedConversion[] {
    const conflictingIds = new Set(
      plans
        .filter(plan => plan.status === 'converted' && hasTailwindClassConflict(existingClassNames, plan.classNames))
        .map(plan => plan.input.id),
    );
    const flexConflict = plans.some(
      plan => conflictingIds.has(plan.input.id) && flexItemDirectives.has(plan.input.directive),
    );
    return plans.map(plan =>
      plan.status === 'converted' &&
      (conflictingIds.has(plan.input.id) || (flexConflict && flexItemDirectives.has(plan.input.directive)))
        ? {
            status: 'review',
            input: plan.input,
            code: 'class-conflict',
            reason: 'An existing Tailwind utility controls a CSS property generated by this conversion.',
            suggestion: 'Remove or reconcile the conflicting utility before migrating this directive.',
          }
        : plan,
    );
  }

  planElement(inputs: readonly LocatedFlexLayoutInput[], context: ConversionContext): readonly PlannedConversion[] {
    const flexInputs = inputs.filter(input => flexItemDirectives.has(input.directive));
    if (!flexInputs.length) {
      return preserveRequiredLayoutContext(inputs.map(input => this.plan(input, context)));
    }

    const flex = flexInputs.filter(input => input.directive === 'fxFlex');
    const hasResponsiveFlexMember = flexInputs.some(input => input.breakpoint !== undefined);
    let flexPlans: readonly PlannedConversion[];
    if (flexInputs.some(input => input.binding !== 'literal' || input.breakpoint)) {
      flexPlans = flexInputs.map(input => {
        const ownPlan = this.plan(input, context);
        return input.binding !== 'literal' || input.breakpoint
          ? ownPlan
          : {
              status: 'review',
              input,
              code: 'context-unverified',
              reason: 'The flex sizing group contains a dynamic or responsive member.',
              suggestion: 'Make fxFlex, fxGrow, and fxShrink static or migrate them together manually.',
            };
      });
      if (hasResponsiveFlexMember) {
        flexPlans = flexPlans.map(plan =>
          plan.status === 'converted'
            ? {
                status: 'review',
                input: plan.input,
                code: 'context-unverified',
                reason: 'The flex sizing group contains a responsive member.',
                suggestion:
                  'Migrate fxFlex, fxGrow, and fxShrink together after responsive sizing support is available.',
              }
            : plan,
        );
      }
    } else if (flex.length !== 1) {
      flexPlans = flexInputs.map(input => ({
        status: 'invalid',
        input,
        code: 'invalid-value',
        reason: flex.length
          ? 'Multiple fxFlex inputs cannot form one static flex item.'
          : `${input.directive} requires fxFlex.`,
        suggestion: 'Keep one static fxFlex directive or migrate this flex item manually.',
      }));
    } else {
      const layout = staticLayoutContext(context.parent?.attributes ?? []);
      const planned = planFlexItem({
        basis: flex[0]?.value ?? '',
        grow: flexInputs.find(input => input.directive === 'fxGrow')?.value,
        shrink: flexInputs.find(input => input.directive === 'fxShrink')?.value,
        layout,
      });
      flexPlans = flexInputs.map(input => {
        if (planned.status === 'converted') {
          return {
            status: 'converted',
            input,
            classNames: input.directive === 'fxFlex' ? planned.classNames : [],
          };
        }
        if (planned.status === 'invalid') {
          return {
            status: 'invalid',
            input,
            code: planned.code,
            reason: `${input.value} is not a valid member of the flex sizing group.`,
            suggestion: 'Correct the static flex value or migrate the group manually.',
          };
        }
        return { ...planned, input };
      });
    }

    const flexPlanById = new Map(flexPlans.map(plan => [plan.input.id, plan]));
    return preserveRequiredLayoutContext(inputs.map(input => flexPlanById.get(input.id) ?? this.plan(input, context)));
  }

  plan(input: LocatedFlexLayoutInput, context: ConversionContext): PlannedConversion {
    if (input.binding === 'property') {
      return toResponsivePlannedConversion(
        input,
        { status: 'converted', classNames: [] },
        this.breakpointCatalog,
        this.responsiveEmitter,
      );
    }

    if (input.directive === 'fxGrow' || input.directive === 'fxShrink') {
      return {
        status: 'invalid',
        input,
        code: 'invalid-value',
        reason: `${input.directive} is owned by an fxFlex directive and cannot be converted independently.`,
        suggestion: 'Add or retain fxFlex and migrate the complete sizing group.',
      };
    }

    if (!supportedDirectives.has(input.directive)) {
      return {
        status: 'unsupported',
        input,
        code: 'target-unsupported',
        reason: `The Tailwind target does not support ${input.directive}.`,
        suggestion: 'Keep the directive and migrate it manually.',
      };
    }

    if (input.directive === 'fxLayoutGap') {
      const layoutValue = staticLayoutContext(context.element.attributes);
      const gap = planLayoutGap(input.value, layoutValue);
      return toResponsivePlannedConversion(input, gap, this.breakpointCatalog, this.responsiveEmitter);
    }

    if (input.directive === 'fxFlex') {
      const flex = planFlexItem({
        basis: input.value,
        layout: staticLayoutContext(context.parent?.attributes ?? []),
      });
      if (flex.status === 'converted') {
        return toResponsivePlannedConversion(input, flex, this.breakpointCatalog, this.responsiveEmitter);
      }
      if (flex.status === 'invalid') {
        return {
          status: 'invalid',
          input,
          code: flex.code,
          reason: `${input.value} is not a supported fxFlex value.`,
          suggestion: 'Correct the value or migrate this directive manually.',
        };
      }
      return { ...flex, input };
    }

    const independent = planIndependentDirective(input);
    if (independent)
      return toResponsivePlannedConversion(input, independent, this.breakpointCatalog, this.responsiveEmitter);
    if (input.directive === 'fxFlexOffset') {
      const layout = staticLayoutContext(context.parent?.attributes ?? []);
      return toResponsivePlannedConversion(
        input,
        planFlexOffset(input.value, layout),
        this.breakpointCatalog,
        this.responsiveEmitter,
      );
    }
    if (input.directive === 'fxLayoutAlign') {
      const layout = staticLayoutContext(context.element.attributes);
      if (layout === undefined) {
        return {
          status: 'review',
          input,
          code: 'context-unverified',
          reason: 'Alignment sizing and direction depend on a dynamic or responsive layout.',
          suggestion: 'Make the layout static or migrate layout and alignment together manually.',
        };
      }
      const alignment = planLayoutAlign(input.value, layout);
      if (alignment.ok) {
        return toResponsivePlannedConversion(
          input,
          { status: 'converted', classNames: alignment.value.classNames },
          this.breakpointCatalog,
          this.responsiveEmitter,
        );
      }
      return {
        status: 'invalid',
        input,
        code: 'invalid-value',
        reason: `${input.value} is not a supported fxLayoutAlign value.`,
        suggestion: 'Correct the value or migrate this directive manually.',
      };
    }

    if (input.directive === 'fxLayout') {
      const layout = planLayout(input.value);
      if (layout.ok) {
        return toResponsivePlannedConversion(
          input,
          { status: 'converted', classNames: layout.value.classNames },
          this.breakpointCatalog,
          this.responsiveEmitter,
        );
      }
    }
    return {
      status: 'invalid',
      input,
      code: 'invalid-value',
      reason: `${input.value} is not a supported ${input.directive} value.`,
      suggestion: 'Correct the value or migrate this directive manually.',
    };
  }
}
