import type { LocatedFlexLayoutInput } from '../../analyzer/flex-layout-attribute.analyzer';
import type { ConversionAdapter, ConversionContext, PlannedConversion } from '../conversion-adapter';
import { planLayoutGap } from './directives/layout-gap.strategy';
import { planFlexItem } from './directives/flex-item.strategy';
import { planFlexOffset } from './directives/flex-offset.strategy';
import type { TailwindStrategyResult } from './tailwind-semantic.model';
import { planLayoutAlign } from './directives/layout-align.strategy';
import { planIndependentDirective } from './independent-directive.registry';
import type { TemplateAttribute } from '../../template/template.model';
import { planLayout } from './directives/layout.strategy';
import { hasTailwindClassConflict } from './tailwind-class-conflict';
import { BreakpointCatalog } from '../../breakpoint/breakpoint-catalog';
import { ResponsiveVariantEmitter } from './responsive-variant.emitter';
import { planResponsiveClasses } from './responsive-plan';
import { ResponsiveFamilyPlanner } from './responsive-family.planner';

const flexItemDirectives = new Set<LocatedFlexLayoutInput['directive']>(['fxFlex', 'fxGrow', 'fxShrink']);

const supportedDirectives = new Set<LocatedFlexLayoutInput['directive']>([
  'fxFlex',
  'fxGrow',
  'fxShrink',
  'fxFlexAlign',
  'fxFlexFill',
  'fxFill',
  'fxFlexOffset',
  'fxFlexOrder',
  'fxLayout',
  'fxLayoutAlign',
  'fxLayoutGap',
]);

function toPlannedConversion(input: LocatedFlexLayoutInput, result: TailwindStrategyResult): PlannedConversion {
  if (result.status === 'converted') return { status: 'converted', input, classNames: result.classNames };
  if (result.status === 'invalid') {
    return {
      status: 'invalid',
      input,
      code: result.code,
      reason: `${input.value} is not a supported ${input.directive} value.`,
      suggestion: 'Correct the value or migrate this directive manually.',
    };
  }
  return { ...result, input };
}

function toResponsivePlannedConversion(
  input: LocatedFlexLayoutInput,
  result: TailwindStrategyResult,
  catalog: BreakpointCatalog,
  emitter: ResponsiveVariantEmitter,
): PlannedConversion {
  return toPlannedConversion(
    input,
    result.status === 'converted' ? planResponsiveClasses(input, result.classNames, catalog, emitter) : result,
  );
}

function staticLayoutContext(attributes: readonly TemplateAttribute[]): string | undefined {
  const layouts = attributes.filter(
    attribute => attribute.name === 'fxLayout' || attribute.name.startsWith('fxLayout.'),
  );
  if (!layouts.length) return 'row';
  if (layouts.length !== 1) return undefined;
  const layout = layouts[0];
  return layout?.name === 'fxLayout' && layout.binding === 'literal' ? layout.value : undefined;
}

export class TailwindAdapter implements ConversionAdapter {
  readonly name = 'tailwind' as const;
  private readonly breakpointCatalog = new BreakpointCatalog();
  private readonly responsiveEmitter = new ResponsiveVariantEmitter();
  private readonly responsiveFamilyPlanner = new ResponsiveFamilyPlanner(
    this.breakpointCatalog,
    this.responsiveEmitter,
  );

  resolveClassConflicts(
    plans: readonly PlannedConversion[],
    existingClassNames: readonly string[],
  ): readonly PlannedConversion[] {
    const conflictingIds = new Set(
      plans
        .filter(plan => plan.status === 'converted' && hasTailwindClassConflict(existingClassNames, plan.classNames))
        .map(plan => plan.input.id),
    );
    const flexConflict = plans.some(
      plan => conflictingIds.has(plan.input.id) && flexItemDirectives.has(plan.input.directive),
    );
    return plans.map(plan =>
      plan.status === 'converted' &&
      (conflictingIds.has(plan.input.id) || (flexConflict && flexItemDirectives.has(plan.input.directive)))
        ? {
            status: 'review',
            input: plan.input,
            code: 'class-conflict',
            reason: 'An existing Tailwind utility controls a CSS property generated by this conversion.',
            suggestion: 'Remove or reconcile the conflicting utility before migrating this directive.',
          }
        : plan,
    );
  }

  planElement(inputs: readonly LocatedFlexLayoutInput[], context: ConversionContext): readonly PlannedConversion[] {
    return this.responsiveFamilyPlanner.plan(inputs, { ...context, inputs }, (input, itemContext) =>
      this.planSemantic(input, itemContext),
    );
  }

  plan(input: LocatedFlexLayoutInput, context: ConversionContext): PlannedConversion {
    const semantic = this.planSemantic(input, context);
    if (semantic.status !== 'converted') return semantic;
    return toResponsivePlannedConversion(
      input,
      { status: 'converted', classNames: semantic.classNames },
      this.breakpointCatalog,
      this.responsiveEmitter,
    );
  }

  private planSemantic(input: LocatedFlexLayoutInput, context: ConversionContext): PlannedConversion {
    if (input.binding === 'property') {
      return toPlannedConversion(
        input,
        planResponsiveClasses(input, [], this.breakpointCatalog, this.responsiveEmitter),
      );
    }

    if (!supportedDirectives.has(input.directive)) {
      return {
        status: 'unsupported',
        input,
        code: 'target-unsupported',
        reason: `The Tailwind target does not support ${input.directive}.`,
        suggestion: 'Keep the directive and migrate it manually.',
      };
    }

    if (input.directive === 'fxLayoutGap') {
      const layoutValue = context.activeLayout ?? staticLayoutContext(context.element.attributes);
      const gap = planLayoutGap(input.value, layoutValue);
      return toPlannedConversion(input, gap);
    }

    if (flexItemDirectives.has(input.directive)) {
      const flexInputs = (context.inputs ?? [input]).filter(item => flexItemDirectives.has(item.directive));
      const sameBreakpoint = (item: LocatedFlexLayoutInput) => item.breakpoint === input.breakpoint;
      const atBreakpoint = (directive: LocatedFlexLayoutInput['directive']) =>
        flexInputs.filter(item => item.directive === directive && sameBreakpoint(item));
      const atBase = (directive: LocatedFlexLayoutInput['directive']) =>
        flexInputs.filter(item => item.directive === directive && item.breakpoint === undefined);
      const exactFlex = atBreakpoint('fxFlex');
      const baseFlex = atBase('fxFlex');
      const basis = exactFlex[0] ?? (input.breakpoint ? baseFlex[0] : undefined);
      const exactGrow = atBreakpoint('fxGrow');
      const exactShrink = atBreakpoint('fxShrink');
      const grow = exactGrow[0] ?? (input.breakpoint ? atBase('fxGrow')[0] : undefined);
      const shrink = exactShrink[0] ?? (input.breakpoint ? atBase('fxShrink')[0] : undefined);
      const duplicateMember = [exactFlex, exactGrow, exactShrink].some(items => items.length > 1);
      if (!basis || duplicateMember) {
        return {
          status: 'invalid',
          input,
          code: 'invalid-value',
          reason: basis
            ? 'Multiple flex sizing inputs define the same responsive state.'
            : `${input.directive} requires an active fxFlex value.`,
          suggestion: 'Keep one flex sizing value per breakpoint or migrate this group manually.',
        };
      }
      const flex = planFlexItem({
        basis: basis.value,
        grow: grow?.value,
        shrink: shrink?.value,
        layout: context.activeParentLayout ?? staticLayoutContext(context.parent?.attributes ?? []),
      });
      if (flex.status === 'converted') {
        return toPlannedConversion(input, flex);
      }
      if (flex.status === 'invalid') {
        return {
          status: 'invalid',
          input,
          code: flex.code,
          reason: `${input.value} is not a supported fxFlex value.`,
          suggestion: 'Correct the value or migrate this directive manually.',
        };
      }
      return { ...flex, input };
    }

    const independent = planIndependentDirective(input);
    if (independent) return toPlannedConversion(input, independent);
    if (input.directive === 'fxFlexOffset') {
      const layout = context.activeParentLayout ?? staticLayoutContext(context.parent?.attributes ?? []);
      return toPlannedConversion(input, planFlexOffset(input.value, layout));
    }
    if (input.directive === 'fxLayoutAlign') {
      const layout = context.activeLayout ?? staticLayoutContext(context.element.attributes);
      if (layout === undefined) {
        return {
          status: 'review',
          input,
          code: 'context-unverified',
          reason: 'Alignment sizing and direction depend on a dynamic or responsive layout.',
          suggestion: 'Make the layout static or migrate layout and alignment together manually.',
        };
      }
      const alignment = planLayoutAlign(input.value, layout);
      if (alignment.ok) {
        return toPlannedConversion(input, { status: 'converted', classNames: alignment.value.classNames });
      }
      return {
        status: 'invalid',
        input,
        code: 'invalid-value',
        reason: `${input.value} is not a supported fxLayoutAlign value.`,
        suggestion: 'Correct the value or migrate this directive manually.',
      };
    }

    if (input.directive === 'fxLayout') {
      const layout = planLayout(input.value);
      if (layout.ok) {
        return toPlannedConversion(input, { status: 'converted', classNames: layout.value.classNames });
      }
    }
    return {
      status: 'invalid',
      input,
      code: 'invalid-value',
      reason: `${input.value} is not a supported ${input.directive} value.`,
      suggestion: 'Correct the value or migrate this directive manually.',
    };
  }
}
